### ISSUE TITLE
Result of printing image base64

### ISSUE THREAD

**Issue by stefanwilliam96** [srehanuddin/Cordova-Plugin-Bluetooth-Printer#71]
i already convert my html to canvas, but the result is like ALIEN WORDS ... can someone help me please ? thanks a lot

**Comment by CesarBalzer** [comment]
Please read discussion [#1](https://github.com/srehanuddin/Cordova-Plugin-Bluetooth-Printer/issues/1)

**Comment by stefanwilliam96** [comment]
> Please read discussion [#1](https://github.com/srehanuddin/Cordova-Plugin-Bluetooth-Printer/issues/1)

did you suggest me to use bixolon print ? i think not every bluetooth printer can read base64 image.

i already try with 2 different bluetooth printer. The first one is MPT-II and this plugin is worked, but if i try with the second one > bluetooth printer P58C, the result is alien words

**Comment by CesarBalzer** [comment]
@stefanwilliam96  I'm doing tests without base64, passing the image path directly to the print, I already got a positive test result, the complicated one and test the plugin change, I still do not know a correct way to debug this.
As soon as I finish the tests I will be uploading a new repo for it and I will give you the feedback

**Comment by stefanwilliam96** [comment]
> @stefanwilliam96 I'm doing tests without base64, passing the image path directly to the print, I already got a positive test result, the complicated one and test the plugin change, I still do not know a correct way to debug this.
> As soon as I finish the tests I will be uploading a new repo for it and I will give you the feedback

okay, thanks for reply me, i'll try to find another way and plugin too ...

**Comment by CesarBalzer** [comment]
> okay, thanks for reply me, i'll try to find another way and plugin too ...

I've been thinking, if you have the manual of this printer, see which one and the command that cancels the Chinese characters, may be the problem you are facing

**Comment by stefanwilliam96** [comment]
> I've been thinking, if you have the manual of this printer, see which one and the command that cancels the Chinese characters, may be the problem you are facing

i already see the manual of this printer and i got nothing ... hmmm how about other plugin, do you have any suggestion ?

**Comment by stefanwilliam96** [comment]
> > okay, thanks for reply me, i'll try to find another way and plugin too ...
> 
> I've been thinking, if you have the manual of this printer, see which one and the command that cancels the Chinese characters, may be the problem you are facing

Hey !!! i already found the SOLUTION !!! i use bluetooth printer plugin from cirrushr https://github.com/cirrushr/Cordova-Plugin-Bluetooth-Printer ... and its worked perfectly for any bluetooth printer !! Thanks for helping me dude

**Comment by CesarBalzer** [comment]
Ok, close the topic with SOLVED please.

**Comment by guestisp** [comment]
> Hey !!! i already found the SOLUTION !!! i use bluetooth printer plugin from cirrushr https://github.com/cirrushr/Cordova-Plugin-Bluetooth-Printer ... and its worked perfectly for any bluetooth printer !! Thanks for helping me dude

I'm unable to print an image even with that plugin.

**Comment by CesarBalzer** [comment]
> I'm unable to print an image even with that plugin.

Are you trying to print with base64 or the image path?

**Comment by guestisp** [comment]
base64.

I'm trying almost every version of this plugin, even yours doesn't work .

**Comment by CesarBalzer** [comment]
Check that size and this image, if it is bigger than 300x300px will give problems.
Take this base64 and test to see
[https://pastebin.com/TqLPzMeY](https://pastebin.com/TqLPzMeY)

**Comment by guestisp** [comment]
It doesn't work. It prints garbage.

**Comment by CesarBalzer** [comment]
What is the model of your printer? Create a pastebin of the code that you are trying, who knows I can help you

**Comment by guestisp** [comment]
https://pastebin.com/iL0MLMVi

I'm able to print a simple text (but line feed doesn't work) and the image is printing garbage even with `print` or `printImage` methods.

I'm using a excelvan hop-e58. The print test done by printer itself is printig properly images, text, text formatting and so on.

**Comment by CesarBalzer** [comment]
I made some changes on my fork for you to test, I also mounted the javascript of how I did the tests on my MTP-II printer.
[https://pastebin.com/cZ1jXpny](https://pastebin.com/cZ1jXpny)

Install my version and test please with the code I passed, here it worked 100%

**Comment by guestisp** [comment]
Image printing now works. Thank you.
But now I'm unable to print a simple text with `BTPrinter.printText('Hello World');`
I'm getting this:
```
Uncaught (in promise) TypeError: callback.success.apply is not a function
    at Object.callbackFromNative (cordova.js:291)
    at processMessage (cordova.js:1115)
    at processMessages (cordova.js:1138)
```

**Comment by CesarBalzer** [comment]
I tested the print, here printed right, see the code I changed, I just put the printText function below the printBase64

[https://pastebin.com/YnqY7kat](https://pastebin.com/YnqY7kat)

**Comment by guestisp** [comment]
My mistake
I try again tomorrow

Thank you

**Comment by CesarBalzer** [comment]
After changing the plugin, I suggest turning the printer off and on again

**Comment by guestisp** [comment]
Can you tell me how to change font size and family? In example a bigger bold text with a different font

**Comment by CesarBalzer** [comment]
I'm currently working on this, my application needs these functions, and I'm creating a function just to print title, with size, alignment and font type, as I did with this printBase64 function, I also created one for printing only passing the image path , but this plugin will still take time to come out. Changing the plugin is complex to test.
I suggest you see the doc of your printer, it should have information of which hexadecimal pass to the printPOSCommand function.
In that interval where we add the function printText, you can add like this:

`BTPrinter.printPOSCommand(null, null, "1B");`
`BTPrinter.printPOSCommand(null, null, "61");`
`BTPrinter.printPOSCommand(null, null, "1");` //align center

Pass the hexadecimal to the function in the order as it says in your printer's manual
**One thing I discovered, have to reset to normal, in the case when the text is aligned to the center, send the commands again to align the left, which is the default**

MPT-II Thermal Printer Bluetooth
![captura de tela 2019-01-14 as 15 38 34](https://user-images.githubusercontent.com/13343041/51129805-916f9e00-1812-11e9-82f7-b4b4f659d06a.png)

**Comment by stefanwilliam96** [comment]
> Ok, close the topic with SOLVED please.

how to give solved in this issue ? sorry newbie here haha

**Comment by guestisp** [comment]
It works.
Just a clarification, every time I send something to print , I have to call `BTPrinter.printPOSCommand(null, null, "0A");` ?

Because a simple `printText` doesn't print, the only way to print is to call `BTPrinter.printPOSCommand(null, null, "0A");`

It seems the printer puts everything in a buffer up to a `0A`. Is this correct ?

Another question: in your example I see
```
        BTPrinter.printPOSCommand(null, null, "1C");//cancel chinese characther
        BTPrinter.printPOSCommand(null, null, "2E");//cancel chinese characther
```

I have to cancel the chinese character every time ?

**Comment by CesarBalzer** [comment]
> It works.


Just a clarification, every time I send something to print , I have to call
** it's line feed

 Because a simple `printText` doesn't print, the only way to print is to call 
** Print yes, something is wrong with printer setup

 It seems the printer puts everything in a buffer up to a `0A`. Is this correct ?
** I still do not fully understand how the pos commands input buffer works, I'm working with the new printTitle function and I'm not getting the right time to set the commands back to normal

I have to cancel the chinese character every time
** No need, I cancel when I send the warranty printing that will not return the Chinese characters. Since I am in Brazil, I need to use accentuation, and I had problems with that.

**Comment by guestisp** [comment]
Ok. Now seems to work properly.

Do you know how to use UTF-8 ? Is that possible ?

**Comment by CesarBalzer** [comment]
I use this way:

`mmOutputStream.write (msg.getBytes ("iso-8859-1"));`

With utf-8 I have not tested

**Comment by guestisp** [comment]
This from java code.
I have to change it from javascript.

I've tried with the following:
```
        BTPrinter.printPOSCommand(null, null, "1B");
        BTPrinter.printPOSCommand(null, null, "74");
        BTPrinter.printPOSCommand(null, null, "16");
```

to set WPC1252 as encoding but some chars are still unprinted properly.

UTF-8 would be much better but I don't think it's supported by the printer.

**Comment by CesarBalzer** [comment]
I do not know how to tell you this to confirm. sorry!

**Comment by guestisp** [comment]
Last question: do you know how to align text, on the same line ?

In example:
```
LEFT ALIGNED             RIGHT ALIGNED
```

I've seen from docs that text align calls can be made only on start of the line.

**Comment by stefanwilliam96** [comment]
> Last question: do you know how to align text, on the same line ?
> 
> In example:
> 
> ```
> LEFT ALIGNED             RIGHT ALIGNED
> ```
> I've seen from docs that text align calls can be made only on start of the line.

you can use normal css text align left or right inside <td> tag bro

**Comment by guestisp** [comment]
Any example?
The printer reconize CSS formatting?

**Comment by limkimsan** [comment]
Hi @CesarBalzer , Does Cordova-Plugin-Bluetooth-Printer be able to print from iOS device?
